version: '3.6'
name: "database"
services:
  db:
    container_name: my-mysql-db
    image: mysql:8
    ports:
      - '3306:3306' #
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

volumes:
  db:
    driver: local


